### ISSUE TITLE
Token description text must not be empty

### ISSUE THREAD

**Issue by sunweaver** [gosa-project/gosa-plugins-privacyidea#48]
Users might want to skip entering a Token Description text when registering new tokens. This should be prohibited.

-> Token Description must not be an empty string. (With alert() feedback, maybe).

**Comment by dzatoah** [comment]
It should be discouraged but not prohibited if I understood Arthur correctly.

**Comment by gber** [comment]
That was my understanding, too. If this is wanted, please do not use alert but HTML form validation.

**Comment by dzatoah** [comment]
Btw, if the description is left empty, privacyIDEA fills it with Hardware info e.g. `Yubico U2F EE Serial 157xxxx` (WebAuthn).

**Comment by dzatoah** [comment]
Implemented by: #95
