### ISSUE TITLE
Users should be alerted about unsaved changes before adding a new token

### ISSUE THREAD

**Issue by gber** [gosa-project/gosa-plugins-privacyidea#81]

**Comment by dzatoah** [comment]
@gber: In order to work on this I need a steady codebase, When is your eta for your reorganizing-edit stuff?

**Comment by dzatoah** [comment]
IIRC, this was a downstream-thing only, right? Can this issue be closed?

**Comment by sunweaver** [comment]
This actually is an upstream issue now purely. In the downstream theme, you can either edit LDAP values or register tokens.

In the upstream variant, you change the whole plugin page into edit mode and then can edit LDAP values. To save them you need to use the edit_apply or edit_finish buttons. But you can also register a token after having modified LDAP values (but not yet saved them). For this case, we need an alert or some such, that reminds the user of saving LDAP value changes first before proceeding with token registrations.

**Comment by sunweaver** [comment]
Hasn't this been resolved by https://github.com/gosa-project/gosa-plugins-privacyidea/pull/98 ?

**Comment by dzatoah** [comment]
Yep is has been. Closing.
