### ISSUE TITLE
IMPORTANT:  Check on first hand-shake with privacyIDEA server that the service user is of role 'admin'

### ISSUE THREAD

**Issue by sunweaver** [gosa-project/gosa-plugins-privacyidea#82]
Code taken from GOsa² core, that shows how to do this:

```
    public function auth_service_account(): mixed
    {
        $data = array(
            "username" => $this->pi_config['piServiceAccount'],
            "password" => $this->pi_config['piServicePass'],
            "realm" => $this->pi_config['piServiceRealm'],
        );

        $this->set_curl(PiEndpoints::Auth, "POST", [], $data);
        $this->set_http_header(true);
        $response = $this->get_response();

        // ensure we have an admin account
        if ($this->findRecursive((array)$response, "role") == 'admin') {
            // return the service token for use in further api calls 
            return $this->findRecursive((array)$response, "token");
        }

        /** 
         * TODO: return something, if the given credentials are 
         * invalid or dont have the admin rights
         */
        return false;
    }
```

**Comment by sunweaver** [comment]
If the service user is not a privacyIDEA admin, the uid field will be ignored on the privacyIDEA API side and privacyIDEA will always operate on tokens owned by the service user. Thanks to @gber for spotting this.

**Comment by dzatoah** [comment]
This issue should be fixed upstream in the privacyidea-php-client lib in `public function getAuthToken()`.

**Comment by sunweaver** [comment]
> This issue should be fixed upstream in the privacyidea-php-client lib in `public function getAuthToken()`.
> 
> Quick fix would be to implement `getAuthToken()` ourselves...

It was not last week, when Guido tested it. What commit exactly fixed this? What version of privacyidea-php-client do we need to install?

Writing this, I am sure, you need to double check and test this with a service user that has normal user privileges in privacyIDEA.

**Comment by dzatoah** [comment]
Sorry, I meant that it should be fixed by upstream instead of here. (No fix available, yet) :)

**Comment by sunweaver** [comment]
> Sorry, I meant that it should be fixed by upstream instead of here. (No fix available, yet) :)
> 
> I'll copy the getAuthToken() function and fix it for us. Then I'll send a patch to upstream later on.

Basically, you are right. Practically, please fix it here. (And file a bug upstream).
